[uwsgi]
chdir = /home/ubuntu/my_project/chinese-measure-words
module = website_items.wsgi:application

home = /home/ubuntu/my_project/venv

;socket = /home/ubuntu/my_project/chinese-measure-words/uwsgi.sock
http = 0.0.0.0:8001
chmod-socket = 666

master = true
processes = 4
threads = 2

logto = /home/ubuntu/my_project/chinese-measure-words/logs/uwsgi.log
pidfile = /home/ubuntu/my_project/chinese-measure-words/uwsgi.pid
vacuum = true