# Generated by Django 6.0.5 on 2026-05-27 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HSK1', 'HSK1'), ('HSK2', 'HSK2'), ('HSK3', 'HSK3'), ('HSK4', 'HSK4')], max_length=10, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.level')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['level__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=200)),
                ('measure_word', models.CharField(blank=True, max_length=20)),
                ('example', models.CharField(blank=True, max_length=200)),
                ('audio_zh', models.FileField(blank=True, editable=False, upload_to='audio/zh/')),
                ('audio_en', models.FileField(blank=True, editable=False, upload_to='audio/en/')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
