# Generated by Django 6.0.5 on 2026-05-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.category', verbose_name='所属分类'),
        ),
    ]
