# Generated by Django 6.0.5 on 2026-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_word_order_alter_word_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
