# Generated by Django 6.0.5 on 2026-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_alter_level_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['id'], 'verbose_name': '词汇', 'verbose_name_plural': '词汇'},
        ),
        migrations.AlterField(
            model_name='word',
            name='audio_en',
            field=models.FileField(blank=True, upload_to='audio/en/', verbose_name='英文音频'),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio_zh',
            field=models.FileField(blank=True, upload_to='audio/zh/', verbose_name='中文音频'),
        ),
        migrations.AlterField(
            model_name='word',
            name='chinese',
            field=models.CharField(max_length=50, verbose_name='汉字'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=200, verbose_name='英文释义'),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.CharField(blank=True, max_length=200, verbose_name='例句'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='word',
            name='measure_word',
            field=models.CharField(blank=True, max_length=20, verbose_name='量词'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(max_length=100, verbose_name='拼音'),
        ),
    ]
